version: "3.9"
services:
  web:
    image: "nginx_custome:latest"
    ports:
      - "8000:80"
  database:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
   
        
